### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by rdewolff** [cronofy/Developer-Demo-Starter#1]
When trying to launch the demo, I get the CORS erros and nothing is loaded.

Tried adding:

```js
const cors = require('cors');
```

And adding it in the setup of express:
```js
const app = express();
app.use(cors())
app.set("view engine", "ejs");
app.set("views", process.cwd() + "/app/templates");
app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(__dirname + "/"));
```

But I still get the error messages.

![Screenshot 2020-12-20 at 18 29 16](https://user-images.githubusercontent.com/130704/102719941-45c4a980-42f1-11eb-9540-bd2cb6cb3fba.png)

Any idea how to fix this?

**Comment by s5rommel** [comment]
is this resolved? I'm having the same problem.

**Comment by viperx77** [comment]
Ditto

**Comment by zedrdave** [comment]
It's been 2 years and this issue still has not been resolved or even addressed, yet this is the code being prominently featured in your Dev Tutorial… What gives?

**Comment by CronofyMatt** [comment]
This specific error occurs in one of two situations:

- You have not connected any calendars to your Cronofy account. You will need to [add a calendar](https://docs.cronofy.com/calendar-users/) in order to use the example application.
- You may not have created a `.env` file in the top level directory containing the required client ids and secret values. There is a guide on how to set this file up on the [Set up the SDK](https://docs.cronofy.com/developers/getting-started/online-booking-tutorial/#step-1-set-up-the-sdk) section of the online booking tutorial.

When using the Cronofy API all requests should be sourced from your backend instead of being made directly within your frontend application (unless you are using our [UI elements](https://docs.cronofy.com/developers/ui-elements/)). This is because you would otherwise be leaking your application secrets to the users of your application in the JavaScript, which would allow malicious users to manipulate your calendar events without your consent.

Apologies about the delay in getting back to this issue. I hope that you were able to solve this issue as I understand it has been some time since it was first opened. For support queries you can contact us at [support@cronofy.com](mailto:support@cronofy.com) where our support and engineering teams can help you out.

We will be updating our monitoring of issues being opened on repos to make sure we don’t let issues stagnate in future. We put a lot of time and effort into the quality of our products and this falls below the standards of support and care we offer elsewhere.

Please do reach out to our support team if you continue to have issues with the example app.
